In [33]:
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
### Sentences
sentences=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [35]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [36]:
## Define the vocabulary size
voc_size=10000

In [37]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sentences]
one_hot_repr


[[3147, 5195, 2943, 7487],
 [3147, 5195, 2943, 7293],
 [3147, 1302, 2943, 4484],
 [9605, 471, 8875, 7848, 5081],
 [9605, 471, 8875, 7848, 4814],
 [8918, 3147, 1845, 2943, 466],
 [7920, 3693, 6067, 7848]]

In [38]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [39]:
import numpy as np


In [40]:
sentences_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sentences_length)
print(embedded_docs)

[[   0    0    0    0 3147 5195 2943 7487]
 [   0    0    0    0 3147 5195 2943 7293]
 [   0    0    0    0 3147 1302 2943 4484]
 [   0    0    0 9605  471 8875 7848 5081]
 [   0    0    0 9605  471 8875 7848 4814]
 [   0    0    0 8918 3147 1845 2943  466]
 [   0    0    0    0 7920 3693 6067 7848]]


In [41]:
## feature representation
dimension = 10


In [42]:
model=Sequential()
model.add(Embedding(voc_size,dimension,input_length=sentences_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [43]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step


array([[[ 0.01641368,  0.02151391, -0.02886704, -0.01561213,
         -0.03560926,  0.00198887,  0.04087324, -0.00456239,
         -0.02360049, -0.04808742],
        [ 0.01641368,  0.02151391, -0.02886704, -0.01561213,
         -0.03560926,  0.00198887,  0.04087324, -0.00456239,
         -0.02360049, -0.04808742],
        [ 0.01641368,  0.02151391, -0.02886704, -0.01561213,
         -0.03560926,  0.00198887,  0.04087324, -0.00456239,
         -0.02360049, -0.04808742],
        [ 0.01641368,  0.02151391, -0.02886704, -0.01561213,
         -0.03560926,  0.00198887,  0.04087324, -0.00456239,
         -0.02360049, -0.04808742],
        [ 0.0214158 , -0.04349142, -0.02595327,  0.03365448,
          0.02489192,  0.04349147, -0.04208744,  0.01098301,
         -0.00732454,  0.04036257],
        [-0.03546079,  0.00351576,  0.01104452,  0.04010722,
          0.00346441,  0.04546798,  0.0036273 ,  0.03879463,
         -0.03704577, -0.01950263],
        [ 0.03004884,  0.00833932, -0.04877412, -0.0

In [45]:
embedded_docs[0]

array([   0,    0,    0,    0, 3147, 5195, 2943, 7487], dtype=int32)

In [48]:
model.predict(embedded_docs[0].reshape(1, sentences_length))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[[ 0.01641368,  0.02151391, -0.02886704, -0.01561213,
         -0.03560926,  0.00198887,  0.04087324, -0.00456239,
         -0.02360049, -0.04808742],
        [ 0.01641368,  0.02151391, -0.02886704, -0.01561213,
         -0.03560926,  0.00198887,  0.04087324, -0.00456239,
         -0.02360049, -0.04808742],
        [ 0.01641368,  0.02151391, -0.02886704, -0.01561213,
         -0.03560926,  0.00198887,  0.04087324, -0.00456239,
         -0.02360049, -0.04808742],
        [ 0.01641368,  0.02151391, -0.02886704, -0.01561213,
         -0.03560926,  0.00198887,  0.04087324, -0.00456239,
         -0.02360049, -0.04808742],
        [ 0.0214158 , -0.04349142, -0.02595327,  0.03365448,
          0.02489192,  0.04349147, -0.04208744,  0.01098301,
         -0.00732454,  0.04036257],
        [-0.03546079,  0.00351576,  0.01104452,  0.04010722,
          0.00346441,  0.04546798,  0.0036273 ,  0.03879463,
         -0.03704577, -0.01950263],
        [ 0.03004884,  0.00833932, -0.04877412, -0.0